# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Temp\Mafia_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import sys


class Ui_Mafia(QtWidgets.QWidget):
 
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 604)
        Form.setStyleSheet("QWidget#Form{background-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:0.956409, y2:0.529, stop:0 rgba(47, 47, 47, 255), stop:1 rgba(86, 86, 86, 255))}")
        
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(0, 40, 551, 521))
        self.textBrowser.setStyleSheet("font: 10pt \"나눔스퀘어\";")
        self.textBrowser.setObjectName("textBrowser")

        self.textEdit = QtWidgets.QLineEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 570, 501, 20))
        self.textEdit.setStyleSheet("font: 10pt \"나눔스퀘어\";")
        self.textEdit.setObjectName("textEdit")
        
        self.inputbutton = QtWidgets.QPushButton(Form)
        self.inputbutton.setGeometry(QtCore.QRect(510, 570, 41, 23))
        self.inputbutton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.inputbutton.setObjectName("inputbutton")
        self.to_user1 = QtWidgets.QPushButton(Form)
        self.to_user1.setGeometry(QtCore.QRect(560, 490, 41, 23))
        self.to_user1.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.to_user1.setObjectName("to_user1")
        self.to_user2 = QtWidgets.QPushButton(Form)
        self.to_user2.setGeometry(QtCore.QRect(610, 490, 41, 23))
        self.to_user2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.to_user2.setObjectName("to_user2")
        self.to_user3 = QtWidgets.QPushButton(Form)
        self.to_user3.setGeometry(QtCore.QRect(660, 490, 41, 23))
        self.to_user3.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.to_user3.setObjectName("to_user3")
        self.to_user4 = QtWidgets.QPushButton(Form)
        self.to_user4.setGeometry(QtCore.QRect(560, 520, 41, 23))
        self.to_user4.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.to_user4.setObjectName("to_user4")
        self.to_user5 = QtWidgets.QPushButton(Form)
        self.to_user5.setGeometry(QtCore.QRect(610, 520, 41, 23))
        self.to_user5.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.to_user5.setObjectName("to_user5")
        self.to_user6 = QtWidgets.QPushButton(Form)
        self.to_user6.setGeometry(QtCore.QRect(660, 520, 41, 23))
        self.to_user6.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"나눔스퀘어 Bold\";")
        self.to_user6.setObjectName("to_user6")
        self.Date = QtWidgets.QLabel(Form)
        self.Date.setGeometry(QtCore.QRect(15, 12, 61, 20))
        self.Date.setStyleSheet("font: 11pt \"배달의민족 주아\"; color:rgb(255, 255, 255)")
        self.Date.setObjectName("Date")
        self.Timer = QtWidgets.QLabel(Form)
        self.Timer.setGeometry(QtCore.QRect(510, 20, 56, 12))
        self.Timer.setStyleSheet("font: 11pt \"배달의민족 주아\"; color:rgb(255, 255, 255)")
        self.Timer.setObjectName("Timer")
        self.myname = QtWidgets.QLabel(Form)
        self.myname.setGeometry(QtCore.QRect(620, 80, 61, 16))
        self.myname.setStyleSheet("font: 11pt \"배달의민족 주아\"; color:rgb(255, 255, 255)")
        self.myname.setObjectName("myname")
        self.myjob_image = QtWidgets.QLabel(Form)
        self.myjob_image.setGeometry(QtCore.QRect(620, 220, 56, 12))
        self.myjob_image.setStyleSheet("font: 11pt \"배달의민족 주아\"; color:rgb(255, 255, 255)")
        self.myjob_image.setObjectName("myjob_image")
        self.output_info = QtWidgets.QLabel(Form)
        self.output_info.setGeometry(QtCore.QRect(560, 460, 71, 16))
        self.output_info.setStyleSheet("font: 11pt \"배달의민족 주아\"; color:rgb(255, 255, 255)")
        self.output_info.setObjectName("output_info")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 10, 81, 21))
        self.label.setStyleSheet("font: 12pt \"배달의민족 도현\"; color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(490, 40, 56, 31))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);border-image:url(:/images/images/hat.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def receivedata(self,id):
        global myid
        myid=id
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inputbutton.setText(_translate("Form", "전송"))
        self.to_user1.setText(_translate("Form", "대기중"))
        self.to_user2.setText(_translate("Form", "대기중"))
        self.to_user3.setText(_translate("Form", "대기중"))
        self.to_user4.setText(_translate("Form", "대기중"))
        self.to_user5.setText(_translate("Form", "대기중"))
        self.to_user6.setText(_translate("Form", "대기중"))
        # self.to_user7.setText(_translate("Form", "유저7"))
        # self.to_user8.setText(_translate("Form", "유저8"))
        self.label.setText(_translate("Form", "마피아게임"))
        self.Date.setText(_translate("Form", "날짜"))
        self.Timer.setText(_translate("Form", "시간"))
        self.myname.setText(_translate("Form", "자기닉네임"))
        self.myjob_image.setText(_translate("Form", "직업사진"))
        self.output_info.setText(_translate("Form", "지목하세요"))

    
    def testreceive(self):
        print('정보를 전달받음',myid)
