# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Temp\mafia_study.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chatting = QtWidgets.QTextEdit(self.centralwidget)
        self.chatting.setGeometry(QtCore.QRect(10, 60, 501, 461))
        self.chatting.setObjectName("chatting")
        self.inputchatting = QtWidgets.QLineEdit(self.centralwidget)
        self.inputchatting.setGeometry(QtCore.QRect(10, 530, 441, 20))
        self.inputchatting.setObjectName("inputchatting")
        self.inputChattingButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputChattingButton.setGeometry(QtCore.QRect(460, 530, 51, 23))
        self.inputChattingButton.setObjectName("inputChattingButton")
        self.Day = QtWidgets.QLabel(self.centralwidget)
        self.Day.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.Day.setObjectName("Day")
        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(410, 30, 111, 16))
        self.Time.setObjectName("Time")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(530, 30, 151, 16))
        self.username.setObjectName("username")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(520, 60, 241, 221))
        self.textEdit_2.setObjectName("textEdit_2")
        self.use_to_user1 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user1.setGeometry(QtCore.QRect(520, 340, 51, 21))
        self.use_to_user1.setObjectName("use_to_user1")
        self.use_to_user2 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user2.setGeometry(QtCore.QRect(580, 340, 51, 21))
        self.use_to_user2.setObjectName("use_to_user2")
        self.use_to_user3 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user3.setGeometry(QtCore.QRect(640, 340, 51, 21))
        self.use_to_user3.setObjectName("use_to_user3")
        self.use_to_user4 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user4.setGeometry(QtCore.QRect(700, 340, 51, 21))
        self.use_to_user4.setObjectName("use_to_user4")
        self.use_to_user7 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user7.setGeometry(QtCore.QRect(640, 370, 51, 21))
        self.use_to_user7.setObjectName("use_to_user7")
        self.use_to_user6 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user6.setGeometry(QtCore.QRect(580, 370, 51, 21))
        self.use_to_user6.setObjectName("use_to_user6")
        self.use_to_user5 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user5.setGeometry(QtCore.QRect(520, 370, 51, 21))
        self.use_to_user5.setObjectName("use_to_user5")
        self.use_to_user8 = QtWidgets.QPushButton(self.centralwidget)
        self.use_to_user8.setGeometry(QtCore.QRect(700, 370, 51, 21))
        self.use_to_user8.setObjectName("use_to_user8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 300, 131, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputChattingButton.setText(_translate("MainWindow", "전송"))
        self.Day.setText(_translate("MainWindow", "첫번째 밤"))
        self.Time.setText(_translate("MainWindow", "남은시간 : 02:00 "))
        self.username.setText(_translate("MainWindow", "유저1"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">직업의 사진 뜨는곳</p></body></html>"))
        self.use_to_user1.setText(_translate("MainWindow", "유저1"))
        self.use_to_user2.setText(_translate("MainWindow", "유저2"))
        self.use_to_user3.setText(_translate("MainWindow", "유저3"))
        self.use_to_user4.setText(_translate("MainWindow", "유저4"))
        self.use_to_user7.setText(_translate("MainWindow", "유저7"))
        self.use_to_user6.setText(_translate("MainWindow", "유저6"))
        self.use_to_user5.setText(_translate("MainWindow", "유저5"))
        self.use_to_user8.setText(_translate("MainWindow", "유저8"))
        self.label_4.setText(_translate("MainWindow", "능력 or 투표 사용하기"))
    
    def chatbtnClicked(self):
        self.inputchatting.get
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
